<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>

<body class="hm-gradient">

    <main>

        <div class="container mt-4">
            <nav>
                <a href="index.php">Accueil</a>
                <h1>Mister Cocktail</h1>
                <h5><a href="addCocktail.php">Ajouter un cockatil</a></h5>
            </nav>
            <!-- Grid column -->
            <div class="col-md-12">
                <h2 class="pt-3 pb-4 text-center font-bold font-up deep-purple-text">Search your cocktail</h2>
                <div class="input-group md-form form-sm form-2 pl-0">
                    <input class="form-control my-0 py-1 pl-3 purple-border" type="text" placeholder="Search something here..." aria-label="Search">
                    <span class="input-group-addon waves-effect purple lighten-2" id="basic-addon1"><a><i class="fa fa-search white-text" aria-hidden="true"></i></a></span>
                </div>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
        <!--Table-->
        <table class="table table-striped">
            <!--Table head-->
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nom</th>
                    <th>Description</th>
                    <th>UrlPhoto</th>
                    <th>DateConception</th>
                    <th>PrixMoyen</th>
                    <th>Action</th>
                </tr>
            </thead>
            <!--Table head-->
            <!--Table body-->
            <tbody>
                <?php foreach ($lister as $cocktail) : ?>
                    <tr>
                        <td><?= $cocktail['id'] ?></td>
                        <td><?= $cocktail['nom'] ?></td>
                        <!-- Afin d'éviter une faille XSS la description est converti en texte non interprété par le navigateur web -->
                        <td><?= htmlentities($cocktail['description']) ?></td>
                        <td><?= htmlentities($cocktail['urlPhoto']) ?></td>
                        <td><?= htmlentities($cocktail['anneeConception']) ?></td>
                        <td><?= htmlentities($cocktail['prixMoyen']) ?></td>
                        <td><a href="suppressionCocktail.php?id=<?= $cocktail['id'] ?>">Suppression</a> <a href="editionCocktail.php?id=<?= $cocktail['id'] ?>">Edition</a> <a href="detailsCocktail.php?id=<?= $cocktail['id'] ?>">details</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</body>

</html>