<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>

<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <a href="backOffice.php">Edit/Supp</a>
        <h1>Mister Cocktail</h1>
    </nav>
    <main>
        <div class="container">
            <form action="editionCocktail.php" method="POST">
                <input type="hidden" name="id" value="<?= $lister['id'] ?>">
                <div class="form-group col-4">
                </div>
                <div class="form-group col-8">
                    <label for="nom">Nom :</label>
                    <input type="text" class="form-control" id="nom" name="nom" maxlength="30" value="<?= $lister['nom'] ?>">
                </div>
                <label for="nom">Option :</label>
                <select class="form-control" id="idFamille" name="idFamille">
                    <?php foreach ($famillesCocktails as $famille) : ?>
                        <?php if ($famille['id'] == $cocktail['idFamille']) : ?>
                            <option value="<?= $famille['id'] ?>" selected><?= $famille['nomFamille'] ?></option>
                        <?php else : ?>
                            <option value="<?= $famille['id'] ?>"><?= $famille['nomFamille'] ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
                <div class="form-group col-12">
                    <label for="nom">Description :</label>
                    <textarea class="form-control" id="description" name="description"><?= $lister['description'] ?></textarea>
                </div>
                <div class="form-group col-3">
                    <label for="nom">Année conception :</label>
                    <input type="number" class="form-control" id="anneeConception" name="anneeConception" placeholder="1900" value="<?= $lister['anneeConception'] ?>">
                </div>
                <div class="form-group col-3">
                    <label for="nom">Prix moyen :</label>
                    <input type="text" class="form-control" id="prixMoyen" name="prixMoyen" value="<?= $lister['prixMoyen'] ?>">
                </div> <br>
                <div class="form-group col-12">
                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                </div>
                <button type="submit" class="btn btn-primary mt-2" value="Retour" onclick="history.go(-1)">Retour</button>
            </form>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</body>

</html>