<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>

<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <a href="backOffice.php">Edit/Supp</a>
        <h1>Mister Cocktail</h1>
    </nav>
    <main>
        <?php foreach ($lister as $cocktail) : ?>
            <article class="card cocktail">
                <a href="details_cocktail.php?id=<?= $cocktail['id'] ?>">
                    <img class="card-img-top" src="www/images/cocktails/<?= $cocktail['urlPhoto'] ?>" alt="<?= $cocktail['description'] ?>">
                </a>
                <div class="card-body">
                    <h4 class="card-title"><?= $cocktail['nom'] ?></h4>
                    <p class="card-text"><?= $cocktail['description'] ?></p>
                    <a href="detailsCocktail.php?id=<?= $cocktail['id'] ?>">+</a>
                </div>
            </article>
        <?php endforeach; ?>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</body>

</html>